export default {
  name: "HiVPN",
  networks: {
    "56": {
      id: 56,
      name: "BNB Smart Chain",
      network: "bsc",
      nativeCurrency: { name: "BNB", symbol: "BNB", decimals: 18 },
      rpcUrls: {
        default: "https://bsc-dataseed.binance.org",
        public: "https://bsc-dataseed.binance.org",
      },
      blockExplorers: {
        etherscan: {
          name: "Etherscan",
          url: "https://bscscan.com/",
        },
        default: {
          name: "Etherscan",
          url: "https://bscscan.com/",
        },
      },
      testnet: false,
    },
    "97": {
      id: 97,
      name: "BNB Smart Chain Testnet",
      network: "bsc-testnet",
      nativeCurrency: { name: "BNB", symbol: "BNB", decimals: 18 },
      rpcUrls: {
        default: "https://data-seed-prebsc-1-s1.binance.org:8545",
        public: "https://data-seed-prebsc-1-s1.binance.org:8545",
      },
      blockExplorers: {
        etherscan: {
          name: "Etherscan",
          url: "https://testnet.bscscan.com/",
        },
        default: {
          name: "Etherscan",
          url: "https://testnet.bscscan.com/",
        },
      },
      testnet: true,
    },
  },
  abi: [
    {
      inputs: [
        { internalType: "address[]", name: "tokens", type: "address[]" },
        { internalType: "address[]", name: "feeds", type: "address[]" },
      ],
      stateMutability: "nonpayable",
      type: "constructor",
    },
    {
      anonymous: false,
      inputs: [
        {
          indexed: true,
          internalType: "address",
          name: "user",
          type: "address",
        },
        {
          indexed: true,
          internalType: "address",
          name: "referrer",
          type: "address",
        },
        {
          indexed: false,
          internalType: "uint256",
          name: "planId",
          type: "uint256",
        },
        {
          indexed: false,
          internalType: "uint256",
          name: "value",
          type: "uint256",
        },
      ],
      name: "NewPayment",
      type: "event",
    },
    {
      inputs: [],
      name: "admin",
      outputs: [{ internalType: "address", name: "", type: "address" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [],
      name: "allOptions",
      outputs: [
        { internalType: "uint256", name: "fee", type: "uint256" },
        { internalType: "uint256", name: "more", type: "uint256" },
        { internalType: "uint256", name: "less", type: "uint256" },
        { internalType: "uint256[8]", name: "planIds", type: "uint256[8]" },
        { internalType: "uint256[8]", name: "planPrices", type: "uint256[8]" },
      ],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [],
      name: "allPayments",
      outputs: [{ internalType: "uint256[]", name: "", type: "uint256[]" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [],
      name: "allPriceFeeds",
      outputs: [{ internalType: "address[]", name: "", type: "address[]" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [],
      name: "allTokens",
      outputs: [{ internalType: "address[]", name: "", type: "address[]" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [],
      name: "allTokensDetails",
      outputs: [
        { internalType: "address[]", name: "addresses", type: "address[]" },
        { internalType: "string[]", name: "symbols", type: "string[]" },
        { internalType: "uint256[]", name: "decimals", type: "uint256[]" },
        { internalType: "uint256[]", name: "prices", type: "uint256[]" },
      ],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [
        { internalType: "address[]", name: "tokens", type: "address[]" },
      ],
      name: "batchRemovePriceFeeds",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [
        { internalType: "address[]", name: "tokens", type: "address[]" },
        { internalType: "address[]", name: "feeds", type: "address[]" },
      ],
      name: "batchSetPriceFeeds",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [{ internalType: "address", name: "newAdmin", type: "address" }],
      name: "changeAdmin",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [{ internalType: "uint256", name: "value", type: "uint256" }],
      name: "changeFee",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [{ internalType: "address", name: "newOwner", type: "address" }],
      name: "changeOwner",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [
        { internalType: "uint256", name: "id", type: "uint256" },
        {
          components: [
            { internalType: "address", name: "user", type: "address" },
            { internalType: "uint256", name: "time", type: "uint256" },
            { internalType: "address", name: "token", type: "address" },
            { internalType: "uint256", name: "value", type: "uint256" },
            { internalType: "uint256", name: "planId", type: "uint256" },
            { internalType: "uint256", name: "amount", type: "uint256" },
          ],
          internalType: "struct IPayable.Payment",
          name: "detail",
          type: "tuple",
        },
      ],
      name: "changePaymentDetail",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [{ internalType: "uint8", name: "value", type: "uint8" }],
      name: "changePercentLess",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [{ internalType: "uint8", name: "value", type: "uint8" }],
      name: "changePercentMore",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [
        { internalType: "uint8", name: "index", type: "uint8" },
        { internalType: "uint40", name: "id", type: "uint40" },
      ],
      name: "changePlanId",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [
        { internalType: "uint8", name: "index", type: "uint8" },
        { internalType: "uint40", name: "price", type: "uint40" },
      ],
      name: "changePrice",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [],
      name: "cleanTokenList",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [{ internalType: "address", name: "token", type: "address" }],
      name: "feedExists",
      outputs: [{ internalType: "bool", name: "", type: "bool" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [{ internalType: "address", name: "feed", type: "address" }],
      name: "feedPrice",
      outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [{ internalType: "uint256", name: "value", type: "uint256" }],
      name: "findPlan",
      outputs: [{ internalType: "uint8", name: "plan", type: "uint8" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [],
      name: "owner",
      outputs: [{ internalType: "address", name: "", type: "address" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [
        { internalType: "uint256", name: "id", type: "uint256" },
        { internalType: "uint256", name: "plan", type: "uint256" },
        { internalType: "address", name: "token", type: "address" },
        { internalType: "uint256", name: "amount", type: "uint256" },
        { internalType: "address", name: "referrer", type: "address" },
      ],
      name: "pay",
      outputs: [],
      stateMutability: "payable",
      type: "function",
    },
    {
      inputs: [],
      name: "paymentCount",
      outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [{ internalType: "uint256", name: "index", type: "uint256" }],
      name: "paymentDetailByIndex",
      outputs: [
        {
          components: [
            { internalType: "address", name: "user", type: "address" },
            { internalType: "uint256", name: "time", type: "uint256" },
            { internalType: "address", name: "token", type: "address" },
            { internalType: "uint256", name: "value", type: "uint256" },
            { internalType: "uint256", name: "planId", type: "uint256" },
            { internalType: "uint256", name: "amount", type: "uint256" },
          ],
          internalType: "struct IPayable.Payment",
          name: "",
          type: "tuple",
        },
      ],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [{ internalType: "uint256", name: "id", type: "uint256" }],
      name: "paymentDetails",
      outputs: [
        { internalType: "address", name: "user", type: "address" },
        { internalType: "uint256", name: "amount", type: "uint256" },
        { internalType: "uint256", name: "planId", type: "uint256" },
      ],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      name: "paymentList",
      outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      name: "payments",
      outputs: [
        { internalType: "address", name: "user", type: "address" },
        { internalType: "uint256", name: "time", type: "uint256" },
        { internalType: "address", name: "token", type: "address" },
        { internalType: "uint256", name: "value", type: "uint256" },
        { internalType: "uint256", name: "planId", type: "uint256" },
        { internalType: "uint256", name: "amount", type: "uint256" },
      ],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [{ internalType: "address", name: "", type: "address" }],
      name: "priceFeeds",
      outputs: [{ internalType: "address", name: "", type: "address" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [
        { internalType: "address", name: "token", type: "address" },
        { internalType: "address", name: "feed", type: "address" },
      ],
      name: "setPriceFeeds",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [
        { internalType: "address", name: "token", type: "address" },
        { internalType: "uint256", name: "value", type: "uint256" },
      ],
      name: "toToken",
      outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [
        { internalType: "address", name: "token", type: "address" },
        { internalType: "uint256", name: "value", type: "uint256" },
      ],
      name: "toUSD",
      outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      name: "tokenList",
      outputs: [{ internalType: "address", name: "", type: "address" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [{ internalType: "address", name: "token", type: "address" }],
      name: "tokenPrice",
      outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [
        { internalType: "address", name: "user", type: "address" },
        { internalType: "address", name: "token", type: "address" },
      ],
      name: "userTokenAllowance",
      outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [
        { internalType: "address", name: "user", type: "address" },
        { internalType: "address", name: "token", type: "address" },
      ],
      name: "userTokenBalance",
      outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [{ internalType: "address", name: "user", type: "address" }],
      name: "userTokensDetails",
      outputs: [
        { internalType: "string[]", name: "symbols", type: "string[]" },
        { internalType: "uint256[]", name: "balances", type: "uint256[]" },
        { internalType: "uint256[]", name: "allowances", type: "uint256[]" },
      ],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [{ internalType: "uint256", name: "value", type: "uint256" }],
      name: "withdrawBnb",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [
        { internalType: "address", name: "token", type: "address" },
        { internalType: "uint256", name: "value", type: "uint256" },
      ],
      name: "withdrawToken",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
  ],
} as const
